
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

/*!40000 ALTER TABLE `modx_system_settings` DISABLE KEYS */;
REPLACE INTO `modx_system_settings` VALUES ('access_category_enabled','1','combo-boolean','core','authentication',NULL);
REPLACE INTO `modx_system_settings` VALUES ('access_context_enabled','1','combo-boolean','core','authentication',NULL);
REPLACE INTO `modx_system_settings` VALUES ('access_resource_group_enabled','1','combo-boolean','core','authentication',NULL);
REPLACE INTO `modx_system_settings` VALUES ('allow_forward_across_contexts','','combo-boolean','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('allow_manager_login_forgot_password','1','combo-boolean','core','authentication',NULL);
REPLACE INTO `modx_system_settings` VALUES ('allow_multiple_emails','1','combo-boolean','core','authentication',NULL);
REPLACE INTO `modx_system_settings` VALUES ('allow_tags_in_post','','combo-boolean','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('anonymous_sessions','1','combo-boolean','core','session',NULL);
REPLACE INTO `modx_system_settings` VALUES ('archive_with','','combo-boolean','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('auto_check_pkg_updates','1','combo-boolean','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('auto_check_pkg_updates_cache_expire','15','numberfield','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('auto_isfolder','1','combo-boolean','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('auto_menuindex','1','combo-boolean','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('automatic_alias','1','combo-boolean','core','furls',NULL);
REPLACE INTO `modx_system_settings` VALUES ('automatic_template_assignment','sibling','textfield','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('base_help_url','//docs.modx.com/help/','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('blocked_minutes','60','numberfield','core','authentication',NULL);
REPLACE INTO `modx_system_settings` VALUES ('cache_alias_map','1','combo-boolean','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('cache_context_settings','1','combo-boolean','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('cache_db','','combo-boolean','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('cache_db_expires','0','numberfield','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('cache_db_session','','combo-boolean','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('cache_db_session_lifetime','','numberfield','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('cache_default','1','combo-boolean','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('cache_expires','0','numberfield','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('cache_format','0','numberfield','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('cache_handler','xPDO\\Cache\\xPDOFileCache','textfield','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('cache_lang_js','1','combo-boolean','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('cache_lexicon_topics','1','combo-boolean','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('cache_noncore_lexicon_topics','1','combo-boolean','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('cache_resource','1','combo-boolean','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('cache_resource_clear_partial','','combo-boolean','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('cache_resource_expires','0','numberfield','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('cache_scripts','1','combo-boolean','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('clear_cache_refresh_trees','','combo-boolean','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('compress_css','1','combo-boolean','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('compress_js','1','combo-boolean','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('confirm_navigation','1','combo-boolean','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('container_suffix','/','textfield','core','furls',NULL);
REPLACE INTO `modx_system_settings` VALUES ('context_tree_sort','1','combo-boolean','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('context_tree_sortby','rank','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('context_tree_sortdir','ASC','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('cultureKey','ru','modx-combo-language','core','language','2025-04-06 13:00:18');
REPLACE INTO `modx_system_settings` VALUES ('date_timezone','','textfield','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('debug','','numberfield','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('default_content_type','1','modx-combo-content-type','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('default_context','web','modx-combo-context','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('default_duplicate_publish_option','preserve','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('default_media_source','1','modx-combo-source','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('default_media_source_type','MODX\\Revolution\\Sources\\modFileMediaSource','modx-combo-source-type','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('default_per_page','20','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('default_template','1','modx-combo-template','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('default_username','(anonymous)','textfield','core','session',NULL);
REPLACE INTO `modx_system_settings` VALUES ('emailsender','oomarkizoo@mail.ru','textfield','core','authentication','2025-04-06 13:00:18');
REPLACE INTO `modx_system_settings` VALUES ('enable_dragdrop','1','combo-boolean','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('enable_gravatar','','combo-boolean','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('enable_template_picker_in_tree','1','combo-boolean','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('error_log_filename','error.log','textfield','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('error_log_filepath','','textfield','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('error_page','1','numberfield','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('failed_login_attempts','5','numberfield','core','authentication',NULL);
REPLACE INTO `modx_system_settings` VALUES ('feed_modx_news','https://feeds.feedburner.com/modx-announce','textfield','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('feed_modx_news_enabled','1','combo-boolean','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('feed_modx_security','https://forums.modx.com/board.xml?board=294','textfield','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('feed_modx_security_enabled','1','combo-boolean','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('form_customization_use_all_groups','','combo-boolean','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('forward_merge_excludes','type,published,class_key','textfield','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('friendly_alias_lowercase_only','1','combo-boolean','core','furls',NULL);
REPLACE INTO `modx_system_settings` VALUES ('friendly_alias_max_length','0','numberfield','core','furls',NULL);
REPLACE INTO `modx_system_settings` VALUES ('friendly_alias_realtime','','combo-boolean','core','furls',NULL);
REPLACE INTO `modx_system_settings` VALUES ('friendly_alias_restrict_chars','pattern','textfield','core','furls',NULL);
REPLACE INTO `modx_system_settings` VALUES ('friendly_alias_restrict_chars_pattern','/[\\0\\x0B\\t\\n\\r\\f\\a&=+%#<>\"~:`@\\?\\[\\]\\{\\}\\|\\^\'\\\\]/','textfield','core','furls',NULL);
REPLACE INTO `modx_system_settings` VALUES ('friendly_alias_strip_element_tags','1','combo-boolean','core','furls',NULL);
REPLACE INTO `modx_system_settings` VALUES ('friendly_alias_translit','none','textfield','core','furls',NULL);
REPLACE INTO `modx_system_settings` VALUES ('friendly_alias_translit_class','translit.modTransliterate','textfield','core','furls',NULL);
REPLACE INTO `modx_system_settings` VALUES ('friendly_alias_translit_class_path','{core_path}components/','textfield','core','furls',NULL);
REPLACE INTO `modx_system_settings` VALUES ('friendly_alias_trim_chars','/.-_','textfield','core','furls',NULL);
REPLACE INTO `modx_system_settings` VALUES ('friendly_alias_word_delimiter','-','textfield','core','furls',NULL);
REPLACE INTO `modx_system_settings` VALUES ('friendly_alias_word_delimiters','-_','textfield','core','furls',NULL);
REPLACE INTO `modx_system_settings` VALUES ('friendly_urls','0','combo-boolean','core','furls','2025-04-06 19:37:25');
REPLACE INTO `modx_system_settings` VALUES ('friendly_urls_strict','','combo-boolean','core','furls',NULL);
REPLACE INTO `modx_system_settings` VALUES ('global_duplicate_uri_check','','combo-boolean','core','furls',NULL);
REPLACE INTO `modx_system_settings` VALUES ('hidemenu_default','','combo-boolean','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('inline_help','1','combo-boolean','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('link_tag_scheme','-1','textfield','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('locale','','textfield','core','language',NULL);
REPLACE INTO `modx_system_settings` VALUES ('lock_ttl','360','numberfield','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('log_deprecated','1','combo-boolean','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('log_level','1','numberfield','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('log_snippet_not_found','1','combo-boolean','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('log_target','FILE','textfield','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('login_background_image','','textfield','core','authentication',NULL);
REPLACE INTO `modx_system_settings` VALUES ('login_help_button','','combo-boolean','core','authentication',NULL);
REPLACE INTO `modx_system_settings` VALUES ('login_logo','','textfield','core','authentication',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mail_charset','UTF-8','modx-combo-charset','core','mail',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mail_dkim_domain','','textfield','core','mail',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mail_dkim_identity','','textfield','core','mail',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mail_dkim_passphrase','','text-password','core','mail',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mail_dkim_privatekeyfile','','textfield','core','mail',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mail_dkim_privatekeystring','','textfield','core','mail',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mail_dkim_selector','','textfield','core','mail',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mail_encoding','8bit','textfield','core','mail',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mail_smtp_auth','','combo-boolean','core','mail',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mail_smtp_autotls','1','combo-boolean','core','mail',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mail_smtp_helo','','textfield','core','mail',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mail_smtp_hosts','localhost','textfield','core','mail',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mail_smtp_keepalive','','combo-boolean','core','mail',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mail_smtp_pass','','text-password','core','mail',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mail_smtp_port','587','numberfield','core','mail',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mail_smtp_secure','','textfield','core','mail',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mail_smtp_single_to','','combo-boolean','core','mail',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mail_smtp_timeout','10','numberfield','core','mail',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mail_smtp_user','','textfield','core','mail',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mail_use_smtp','','combo-boolean','core','mail',NULL);
REPLACE INTO `modx_system_settings` VALUES ('main_nav_parent','topnav','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('manager_date_format','Y-m-d','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('manager_datetime_empty_value','—','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('manager_datetime_separator',', ','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('manager_direction','ltr','textfield','core','language',NULL);
REPLACE INTO `modx_system_settings` VALUES ('manager_favicon_url','favicon.ico','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('manager_login_url_alternate','','textfield','core','authentication',NULL);
REPLACE INTO `modx_system_settings` VALUES ('manager_logo','','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('manager_theme','default','modx-combo-manager-theme','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('manager_time_format','H:i','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('manager_tooltip_delay','2300','numberfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('manager_tooltip_enable','1','combo-boolean','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('manager_use_fullname','','combo-boolean','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('manager_week_start','0','numberfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mgr_source_icon','icon-folder-open-o','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mgr_tree_icon_context','tree-context','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('modx_browser_default_sort','name','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('modx_browser_default_viewmode','grid','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('modx_browser_tree_hide_files','1','combo-boolean','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('modx_browser_tree_hide_tooltips','1','combo-boolean','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('modx_charset','UTF-8','modx-combo-charset','core','language',NULL);
REPLACE INTO `modx_system_settings` VALUES ('new_file_permissions','0664','textfield','core','',NULL);
REPLACE INTO `modx_system_settings` VALUES ('package_installer_at_top','1','combo-boolean','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('parser_recurse_uncacheable','1','combo-boolean','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('password_generated_length','10','numberfield','core','authentication',NULL);
REPLACE INTO `modx_system_settings` VALUES ('password_min_length','8','numberfield','core','authentication',NULL);
REPLACE INTO `modx_system_settings` VALUES ('passwordless_activated','0','combo-boolean','core','authentication','2025-04-08 16:12:02');
REPLACE INTO `modx_system_settings` VALUES ('passwordless_expiration','3600','textfield','core','authentication',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_allow_src_above_docroot','','combo-boolean','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_cache_maxage','30','numberfield','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_cache_maxfiles','10000','numberfield','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_cache_maxsize','100','numberfield','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_cache_source_enabled','','combo-boolean','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_document_root','','textfield','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_error_bgcolor','CCCCFF','textfield','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_error_fontsize','1','numberfield','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_error_textcolor','FF0000','textfield','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_far','C','textfield','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_imagemagick_path','','textfield','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_nohotlink_enabled','1','combo-boolean','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_nohotlink_erase_image','1','combo-boolean','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_nohotlink_text_message','Off-server thumbnailing is not allowed','textfield','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_nohotlink_valid_domains','{http_host}','textfield','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_nooffsitelink_enabled','','combo-boolean','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_nooffsitelink_erase_image','1','combo-boolean','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_nooffsitelink_require_refer','','combo-boolean','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_nooffsitelink_text_message','Off-server linking is not allowed','textfield','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_nooffsitelink_valid_domains','{http_host}','textfield','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_nooffsitelink_watermark_src','','textfield','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_zoomcrop','0','textfield','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('preserve_menuindex','','combo-boolean','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('principal_targets','MODX\\Revolution\\modAccessContext,MODX\\Revolution\\modAccessResourceGroup,MODX\\Revolution\\modAccessCategory,MODX\\Revolution\\Sources\\modAccessMediaSource,MODX\\Revolution\\modAccessNamespace','textfield','core','authentication',NULL);
REPLACE INTO `modx_system_settings` VALUES ('proxy_auth_type','BASIC','textfield','core','proxy',NULL);
REPLACE INTO `modx_system_settings` VALUES ('proxy_host','','textfield','core','proxy',NULL);
REPLACE INTO `modx_system_settings` VALUES ('proxy_password','','text-password','core','proxy',NULL);
REPLACE INTO `modx_system_settings` VALUES ('proxy_port','','numberfield','core','proxy',NULL);
REPLACE INTO `modx_system_settings` VALUES ('proxy_username','','textfield','core','proxy',NULL);
REPLACE INTO `modx_system_settings` VALUES ('publish_default','','combo-boolean','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('quick_search_in_content','1','combo-boolean','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('quick_search_result_max','10','numberfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('request_controller','index.php','textfield','core','gateway',NULL);
REPLACE INTO `modx_system_settings` VALUES ('request_method_strict','','combo-boolean','core','gateway',NULL);
REPLACE INTO `modx_system_settings` VALUES ('request_param_alias','q','textfield','core','gateway',NULL);
REPLACE INTO `modx_system_settings` VALUES ('request_param_id','id','textfield','core','gateway',NULL);
REPLACE INTO `modx_system_settings` VALUES ('resource_static_allow_absolute','0','combo-boolean','core','static_resources',NULL);
REPLACE INTO `modx_system_settings` VALUES ('resource_static_path','{assets_path}','textfield','core','static_resources',NULL);
REPLACE INTO `modx_system_settings` VALUES ('resource_tree_node_name','pagetitle','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('resource_tree_node_name_fallback','alias','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('resource_tree_node_tooltip','','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('richtext_default','1','combo-boolean','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('search_default','1','combo-boolean','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('send_poweredby_header','1','combo-boolean','core','system','2025-04-06 13:00:18');
REPLACE INTO `modx_system_settings` VALUES ('server_offset_time','0','numberfield','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('session_cookie_domain','','textfield','core','session',NULL);
REPLACE INTO `modx_system_settings` VALUES ('session_cookie_httponly','1','combo-boolean','core','session',NULL);
REPLACE INTO `modx_system_settings` VALUES ('session_cookie_lifetime','604800','numberfield','core','session',NULL);
REPLACE INTO `modx_system_settings` VALUES ('session_cookie_path','','textfield','core','session',NULL);
REPLACE INTO `modx_system_settings` VALUES ('session_cookie_samesite','','textfield','core','session',NULL);
REPLACE INTO `modx_system_settings` VALUES ('session_cookie_secure','','combo-boolean','core','session',NULL);
REPLACE INTO `modx_system_settings` VALUES ('session_gc_maxlifetime','604800','textfield','core','session',NULL);
REPLACE INTO `modx_system_settings` VALUES ('session_handler_class','MODX\\Revolution\\modSessionHandler','textfield','core','session',NULL);
REPLACE INTO `modx_system_settings` VALUES ('session_name','','textfield','core','session',NULL);
REPLACE INTO `modx_system_settings` VALUES ('set_header','1','combo-boolean','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('settings_distro','traditional','textfield','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('settings_version','3.1.0-pl','textfield','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('show_tv_categories_header','1','combo-boolean','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('site_name','MODX Revolution','textfield','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('site_start','1','numberfield','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('site_status','1','combo-boolean','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('site_unavailable_message','[[%site_unavailable_message]]','textfield','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('site_unavailable_page','0','numberfield','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('static_elements_automate_chunks','','combo-boolean','core','static_elements',NULL);
REPLACE INTO `modx_system_settings` VALUES ('static_elements_automate_plugins','','combo-boolean','core','static_elements',NULL);
REPLACE INTO `modx_system_settings` VALUES ('static_elements_automate_snippets','','combo-boolean','core','static_elements',NULL);
REPLACE INTO `modx_system_settings` VALUES ('static_elements_automate_templates','','combo-boolean','core','static_elements',NULL);
REPLACE INTO `modx_system_settings` VALUES ('static_elements_automate_tvs','','combo-boolean','core','static_elements',NULL);
REPLACE INTO `modx_system_settings` VALUES ('static_elements_basepath','','textfield','core','static_elements',NULL);
REPLACE INTO `modx_system_settings` VALUES ('static_elements_default_category','0','modx-combo-category','core','static_elements',NULL);
REPLACE INTO `modx_system_settings` VALUES ('static_elements_default_mediasource','0','modx-combo-source','core','static_elements',NULL);
REPLACE INTO `modx_system_settings` VALUES ('static_elements_html_extension','.tpl','textfield','core','static_elements',NULL);
REPLACE INTO `modx_system_settings` VALUES ('symlink_merge_fields','1','combo-boolean','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('syncsite_default','1','combo-boolean','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('topmenu_show_descriptions','1','combo-boolean','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('tree_default_sort','menuindex','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('tree_root_id','0','numberfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('tvs_below_content','','combo-boolean','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('unauthorized_page','1','numberfield','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('upload_file_exists','1','combo-boolean','core','file',NULL);
REPLACE INTO `modx_system_settings` VALUES ('upload_files','aac,au,avi,bmp,css,css.map,doc,docx,eot,gif,gz,htm,html,ico,jpeg,jpg,js,js.map,less,md,mp3,mp4,mpeg,mpg,odb,odf,odg,odp,ods,odt,pdf,png,ppt,pptx,psd,rar,scss,svg,svgz,tar,tgz,tiff,ttf,txt,wav,webp,wmv,woff,woff2,xls,xlsx,xml,z,zip','textfield','core','file',NULL);
REPLACE INTO `modx_system_settings` VALUES ('upload_maxsize','5242880','numberfield','core','file','2025-04-07 18:40:45');
REPLACE INTO `modx_system_settings` VALUES ('upload_translit','1','combo-boolean','core','file',NULL);
REPLACE INTO `modx_system_settings` VALUES ('upload_translit_restrict_chars_pattern','/[\\0\\x0B\\t\\n\\r\\f\\a&=+%#<>\"~:`@\\?\\[\\]\\{\\}\\|\\^\'\\\\]/','textfield','core','file',NULL);
REPLACE INTO `modx_system_settings` VALUES ('use_alias_path','0','combo-boolean','core','furls','2025-04-06 19:37:00');
REPLACE INTO `modx_system_settings` VALUES ('use_context_resource_table','1','combo-boolean','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('use_editor','1','combo-boolean','core','editor',NULL);
REPLACE INTO `modx_system_settings` VALUES ('use_frozen_parent_uris','','combo-boolean','core','furls',NULL);
REPLACE INTO `modx_system_settings` VALUES ('use_multibyte','1','combo-boolean','core','language','2025-04-06 13:00:18');
REPLACE INTO `modx_system_settings` VALUES ('use_weblink_target','','combo-boolean','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('user_nav_parent','usernav','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('welcome_action','welcome','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('welcome_namespace','core','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('welcome_screen','','combo-boolean','core','manager','2025-04-06 13:01:27');
REPLACE INTO `modx_system_settings` VALUES ('welcome_screen_url','//misc.modx.com/revolution/welcome.31.html','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('which_editor','','modx-combo-rte','core','editor',NULL);
REPLACE INTO `modx_system_settings` VALUES ('which_element_editor','','modx-combo-rte','core','editor',NULL);
REPLACE INTO `modx_system_settings` VALUES ('xhtml_urls','1','combo-boolean','core','site',NULL);
/*!40000 ALTER TABLE `modx_system_settings` ENABLE KEYS */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

