
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

/*!40000 ALTER TABLE `modx_deprecated_call` DISABLE KEYS */;
REPLACE INTO `modx_deprecated_call` VALUES (1,1,4,'xPDO\\xPDO::newObject','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php',808);
REPLACE INTO `modx_deprecated_call` VALUES (2,2,4,'xPDO\\xPDO::call','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php',774);
REPLACE INTO `modx_deprecated_call` VALUES (3,2,4,'MODX\\Revolution\\modAccessibleObject::load','/var/www/html/core/src/Revolution/modAccessibleObject.php',106);
REPLACE INTO `modx_deprecated_call` VALUES (4,3,2,'xPDO\\xPDO::newObject','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php',808);
REPLACE INTO `modx_deprecated_call` VALUES (5,4,617,'xPDO\\xPDO::call','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php',774);
REPLACE INTO `modx_deprecated_call` VALUES (6,4,613,'MODX\\Revolution\\modAccessibleObject::load','/var/www/html/core/src/Revolution/modAccessibleObject.php',106);
REPLACE INTO `modx_deprecated_call` VALUES (7,5,909,'xPDO\\xPDO::call','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php',774);
REPLACE INTO `modx_deprecated_call` VALUES (8,5,909,'MODX\\Revolution\\modAccessibleObject::load','/var/www/html/core/src/Revolution/modAccessibleObject.php',106);
REPLACE INTO `modx_deprecated_call` VALUES (9,5,758,'xPDO\\xPDO::newObject','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php',808);
REPLACE INTO `modx_deprecated_call` VALUES (10,6,853,'xPDO\\Om\\xPDOQuery::__construct','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/Om/xPDOQuery.php',122);
REPLACE INTO `modx_deprecated_call` VALUES (11,6,1043,'xPDO\\xPDO::call','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php',774);
REPLACE INTO `modx_deprecated_call` VALUES (12,6,853,'xPDO\\xPDO::getFields','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php',1422);
REPLACE INTO `modx_deprecated_call` VALUES (13,6,329,'MODX\\Revolution\\modAccessibleObject::loadCollection','/var/www/html/core/src/Revolution/modAccessibleObject.php',164);
REPLACE INTO `modx_deprecated_call` VALUES (14,7,67,'xPDO\\Om\\xPDOQuery::join','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/Om/xPDOQuery.php',295);
REPLACE INTO `modx_deprecated_call` VALUES (15,7,67,'xPDO\\xPDO::getTableName','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php',1289);
REPLACE INTO `modx_deprecated_call` VALUES (16,8,18,'MODX\\Revolution\\Registry\\modRegistry::_initRegister','/var/www/html/core/src/Revolution/Registry/modRegistry.php',173);
REPLACE INTO `modx_deprecated_call` VALUES (17,9,38,'xPDO\\xPDO::newObject','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php',808);
REPLACE INTO `modx_deprecated_call` VALUES (18,10,41,'xPDO\\xPDO::call','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php',774);
REPLACE INTO `modx_deprecated_call` VALUES (19,10,39,'xPDO\\Om\\xPDOObject::load','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/Om/xPDOObject.php',402);
REPLACE INTO `modx_deprecated_call` VALUES (20,10,2,'xPDO\\Om\\xPDOQuery::__construct','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/Om/xPDOQuery.php',122);
REPLACE INTO `modx_deprecated_call` VALUES (21,10,2,'xPDO\\xPDO::getPK','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php',1598);
REPLACE INTO `modx_deprecated_call` VALUES (22,10,2,'xPDO\\xPDO::getFields','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php',1422);
REPLACE INTO `modx_deprecated_call` VALUES (23,10,3,'xPDO\\xPDO::newObject','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php',808);
REPLACE INTO `modx_deprecated_call` VALUES (24,11,3,'xPDO\\xPDO::newObject','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php',808);
REPLACE INTO `modx_deprecated_call` VALUES (25,12,3,'xPDO\\xPDO::call','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php',774);
REPLACE INTO `modx_deprecated_call` VALUES (26,12,3,'MODX\\Revolution\\modAccessibleObject::load','/var/www/html/core/src/Revolution/modAccessibleObject.php',106);
REPLACE INTO `modx_deprecated_call` VALUES (27,4,27,'xPDO\\xPDO::newObject','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php',808);
REPLACE INTO `modx_deprecated_call` VALUES (28,13,5,'xPDO\\xPDO::newObject','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php',808);
REPLACE INTO `modx_deprecated_call` VALUES (29,13,5,'xPDO\\xPDO::call','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php',774);
REPLACE INTO `modx_deprecated_call` VALUES (30,13,5,'MODX\\Revolution\\modAccessibleObject::load','/var/www/html/core/src/Revolution/modAccessibleObject.php',106);
REPLACE INTO `modx_deprecated_call` VALUES (31,14,17,'xPDO\\xPDO::newObject','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php',808);
REPLACE INTO `modx_deprecated_call` VALUES (32,14,17,'xPDO\\xPDO::call','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php',774);
REPLACE INTO `modx_deprecated_call` VALUES (33,14,17,'xPDO\\Om\\xPDOObject::load','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/Om/xPDOObject.php',402);
REPLACE INTO `modx_deprecated_call` VALUES (34,15,3,'xPDO\\xPDO::newObject','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php',808);
REPLACE INTO `modx_deprecated_call` VALUES (35,16,3,'xPDO\\xPDO::call','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php',774);
REPLACE INTO `modx_deprecated_call` VALUES (36,16,3,'MODX\\Revolution\\modAccessibleObject::load','/var/www/html/core/src/Revolution/modAccessibleObject.php',106);
REPLACE INTO `modx_deprecated_call` VALUES (37,17,510,'xPDO\\xPDO::call','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php',774);
REPLACE INTO `modx_deprecated_call` VALUES (38,17,510,'MODX\\Revolution\\modAccessibleObject::load','/var/www/html/core/src/Revolution/modAccessibleObject.php',106);
REPLACE INTO `modx_deprecated_call` VALUES (39,18,1060,'xPDO\\xPDO::call','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php',774);
REPLACE INTO `modx_deprecated_call` VALUES (40,18,1060,'MODX\\Revolution\\modAccessibleObject::load','/var/www/html/core/src/Revolution/modAccessibleObject.php',106);
REPLACE INTO `modx_deprecated_call` VALUES (41,18,2800,'xPDO\\xPDO::newObject','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php',808);
REPLACE INTO `modx_deprecated_call` VALUES (42,18,225,'xPDO\\xPDO::getPKType','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php',1660);
REPLACE INTO `modx_deprecated_call` VALUES (43,18,225,'xPDO\\xPDO::getPK','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php',1598);
REPLACE INTO `modx_deprecated_call` VALUES (44,19,2373,'xPDO\\xPDO::call','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php',774);
REPLACE INTO `modx_deprecated_call` VALUES (45,19,2373,'xPDO\\Om\\xPDOObject::load','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/Om/xPDOObject.php',402);
REPLACE INTO `modx_deprecated_call` VALUES (46,20,123,'xPDO\\xPDO::getService','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php',1258);
REPLACE INTO `modx_deprecated_call` VALUES (47,6,123,'xPDO\\xPDO::getPKType','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php',1660);
REPLACE INTO `modx_deprecated_call` VALUES (48,6,385,'xPDO\\xPDO::getPK','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php',1598);
REPLACE INTO `modx_deprecated_call` VALUES (49,6,123,'MODX\\Revolution\\modAccessibleObject::load','/var/www/html/core/src/Revolution/modAccessibleObject.php',106);
REPLACE INTO `modx_deprecated_call` VALUES (50,21,18,'xPDO\\xPDO::call','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php',774);
REPLACE INTO `modx_deprecated_call` VALUES (51,21,18,'MODX\\Revolution\\modAccessibleObject::loadCollection','/var/www/html/core/src/Revolution/modAccessibleObject.php',164);
REPLACE INTO `modx_deprecated_call` VALUES (52,17,434,'xPDO\\xPDO::getPKType','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php',1660);
REPLACE INTO `modx_deprecated_call` VALUES (53,17,434,'xPDO\\xPDO::getPK','/var/www/html/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php',1598);
/*!40000 ALTER TABLE `modx_deprecated_call` ENABLE KEYS */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

