
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

/*!40000 ALTER TABLE `modx_site_tmplvar_contentvalues` DISABLE KEYS */;
REPLACE INTO `modx_site_tmplvar_contentvalues` VALUES (1,1,10,'Сайдинг наружный виниловый Альта-Профиль Классика, Светло-серый');
REPLACE INTO `modx_site_tmplvar_contentvalues` VALUES (2,2,10,'1500.00');
REPLACE INTO `modx_site_tmplvar_contentvalues` VALUES (3,3,10,'Классический виниловый сайдинг, изготовленный из прочного и долговечного полимерного материала. Разработан в России – для нашего климата и наших домов.');
REPLACE INTO `modx_site_tmplvar_contentvalues` VALUES (9,9,10,'[{\"MIGX_id\":\"1\",\"image\":\"\\u043a\\u043e\\u0440\\u0430\\u0431\\u0435\\u043b\\u044c\\u043d\\u0430\\u044f-\\u0434\\u043e\\u0441\\u043a\\u0430-0,265-0,5-satin-ral-7004-(2).png\"},{\"MIGX_id\":\"2\",\"image\":\"\\u043a\\u043e\\u0440\\u0430\\u0431\\u0435\\u043b\\u044c\\u043d\\u0430\\u044f-\\u0434\\u043e\\u0441\\u043a\\u0430-0,265-0,5-satin-ral-7004-(3).png\"},{\"MIGX_id\":\"3\",\"image\":\"\\u043a\\u043e\\u0440\\u0430\\u0431\\u0435\\u043b\\u044c\\u043d\\u0430\\u044f-\\u0434\\u043e\\u0441\\u043a\\u0430-0,265-0,5-satin-ral-7004.png\"}]');
REPLACE INTO `modx_site_tmplvar_contentvalues` VALUES (10,1,16,'ЭкоБрус 0,345 0,45 PE с пленкой');
REPLACE INTO `modx_site_tmplvar_contentvalues` VALUES (11,2,16,'1400.00');
REPLACE INTO `modx_site_tmplvar_contentvalues` VALUES (12,10,10,'[{\"MIGX_id\":\"1\",\"brand\":\"Grand Line\",\"country_origin\":\"Россия\",\"guarantee\":\"10 лет\",\"material\":\"сталь\",\"color_shade\":\"Серый\",\"thickness\":\"0,5\",\"coating_thickness\":\"25\",\"overall_width\":\"265\"}]');
REPLACE INTO `modx_site_tmplvar_contentvalues` VALUES (13,3,16,'Металлический сайдинг «ЭкоБрус GL» – это облицовочный материал, предназначенный для обшивки фасадов жилых и промышленных объектов. В сочетании с покрытием Colority® Print, сайдинг «ЭкоБрус GL» имитирует внешний вид клееного бруса, что придает натуральный вид фасаду Вашего дома. Особая геометрия панелей «ЭкоБрус GL» исключает возможность попадания влаги в конструкцию фасада, а значит, дом сохранит неизменный внешний вид на долгие годы.  Преимущества сайдинга ЭкоБрус GL При использовании покрытия Colority® Print, «ЭкоБрус GL» достигает максимального сходства с клееным брусом. Надежное скрытое сцепление панелей придает фасаду здания естественный вид.  Для снижения вероятности повреждения изделия при транспортировке и хранении, сайдинг «ЭкоБрус GL» производится в защитной пленке. «ЭкоБрус GL» экологически безопасный продукт, как и натуральное дерево, но лишен его недостатков.  «ЭкоБрус GL» долговечен, устойчив к выцветанию и перепадам температур.  В отличие от облицовки фасада деревом, металлический сайдинг «ЭкоБрус GL» прост в монтаже и не требует дополнительного послемонтажного ухода. На металлический сайдинг «ЭкоБрус GL» распространяется фирменная письменная гарантия производителя.  «ЭкоБрус GL» подходит для использования как в частном коттеджном строительстве, так и для декорирования фасадов промышленных объектов. В отличии от дерева, металлический сайдинг «ЭкоБрус GL» может применяться на объектах с повышенными требованиями к пожарной безопасности  Широкая линейка покрытий и цветовых решений позволяет воплотить в жизнь любое дизайнерское решение для Вашего фасада.');
REPLACE INTO `modx_site_tmplvar_contentvalues` VALUES (14,9,16,'[{\"MIGX_id\":\"1\",\"image\":\"экобрус-0,345-0,5-satin.png\",\"desc\":\"\"},{\"MIGX_id\":\"2\",\"image\":\"экобрус-0,345-0,5-satin-(2).png\",\"desc\":\"\"}]');
REPLACE INTO `modx_site_tmplvar_contentvalues` VALUES (15,10,16,'[{\"MIGX_id\":\"1\",\"brand\":\"Grand Line\",\"country_origin\":\"Россия\",\"guarantee\":\"5 лет\",\"material\":\"сталь\",\"color_shade\":\"Желтый\",\"thickness\":\"345\",\"coating_thickness\":\"25\",\"overall_width\":\"0,5\"}]');
REPLACE INTO `modx_site_tmplvar_contentvalues` VALUES (16,1,17,'Вертикаль 0,2 gofr 0,5 Satin с пленкой');
REPLACE INTO `modx_site_tmplvar_contentvalues` VALUES (17,2,17,'1250.00');
REPLACE INTO `modx_site_tmplvar_contentvalues` VALUES (18,3,17,'Сайдинг \"Вертикаль\" - облицовочный материал, предназначенный для отделки как жилых, так и промышленных объектов. Также может использоваться в качестве софитов для подшивки карнизных и фронтонных свесов. Оригинальность достигается за счет вертикального крепления панелей. Сочетание сайдинга \"Вертикаль\" с горизонтальным сайдингом может стать интересным дизайнерским решением.');
REPLACE INTO `modx_site_tmplvar_contentvalues` VALUES (19,9,17,'[{\"MIGX_id\":\"2\",\"image\":\"вертикаль-0,2-classic-0,45-pe-с-пленкой-(2).png\",\"desc\":\"\"},{\"MIGX_id\":\"3\",\"image\":\"вертикаль-0,2-classic-0,45-pe-с-пленкой.png\",\"desc\":\"\"}]');
REPLACE INTO `modx_site_tmplvar_contentvalues` VALUES (20,10,17,'[{\"MIGX_id\":\"1\",\"brand\":\"Grand Line\",\"country_origin\":\"Россия\",\"guarantee\":\"10 лет\",\"material\":\"сталь\",\"color_shade\":\"Синий\",\"thickness\":\"0,5\",\"coating_thickness\":\"25\",\"overall_width\":\"200\"}]');
REPLACE INTO `modx_site_tmplvar_contentvalues` VALUES (21,1,18,'Корабельная Доска 0,265 0,5 Satin с пленкой');
REPLACE INTO `modx_site_tmplvar_contentvalues` VALUES (22,2,18,'1200.00');
REPLACE INTO `modx_site_tmplvar_contentvalues` VALUES (23,3,18,'Сайдинг «Корабельная доска» является наиболее популярным в России. Имитирует дощатую обшивку. Благодаря своей форме этот вид профиля прост в монтаже и удобен в эксплуатации. Чаще всего устанавливается горизонтально.        Преимущества:     1. При использовании покрытия Colority® Print металлический сайдинг Корабельная доска достигает максимального сходства с натуральным деревом. Надежное скрытое сцепление панелей придает фасаду здания естественный вид.  2. Сайдинг Корабельная доска производится в защитной пленке. Таким образом, снижается вероятность повреждения изделия при транспортировке и хранении.  3. Сайдинг устойчив к выцветанию, перепадам температур, экологически безопасен.');
REPLACE INTO `modx_site_tmplvar_contentvalues` VALUES (24,9,18,'[{\"MIGX_id\":\"1\",\"image\":\"корабельная-доска-0,265-0,45-(2).png\",\"desc\":\"\"},{\"MIGX_id\":\"2\",\"image\":\"корабельная-доска-0,265-0,45.png\",\"desc\":\"\"}]');
REPLACE INTO `modx_site_tmplvar_contentvalues` VALUES (25,10,18,'[{\"MIGX_id\":\"1\",\"brand\":\"Grand Line\",\"country_origin\":\"Россия\",\"guarantee\":\"10 лет\",\"material\":\"сталь\",\"color_shade\":\"Красный\",\"thickness\":\"0,5\",\"coating_thickness\":\"25\",\"overall_width\":\"265\"}]');
REPLACE INTO `modx_site_tmplvar_contentvalues` VALUES (26,1,19,'Профиль волновой Камея');
REPLACE INTO `modx_site_tmplvar_contentvalues` VALUES (27,2,19,'1650.00');
REPLACE INTO `modx_site_tmplvar_contentvalues` VALUES (28,3,19,'Профиль волновой - отличное решение для создания привлекательных и прочных фасадов и заборов. Отличается не только изысканной формой, но и своей долговечностью.  Волновой профиль Kamea (Камея) - это современный премиум-класс, самое стильное решение для вашего зобора. Изготавливается на европейском оборудовании только из высококачественной стали.  Назначение:  Подходит для частного домостроения, а также для среднего и крупного коттеджного строительства.  Особенности:  эстетичный и современный внешний вид экологически и пожаробезопасен устойчив к выцветанию, гниению, перепадам температур не требует покраски и дополнительного послемонтажного ухода');
REPLACE INTO `modx_site_tmplvar_contentvalues` VALUES (29,9,19,'[{\"MIGX_id\":\"1\",\"image\":\"\\u043f\\u0440\\u043e\\u0444\\u0438\\u043b\\u044c-\\u0432\\u043e\\u043b\\u043d\\u043e\\u0432\\u043e\\u0439-\\u043a\\u0430\\u043c\\u0435\\u044f.png\",\"desc\":\"\"},{\"MIGX_id\":\"2\",\"image\":\"\\u043f\\u0440\\u043e\\u0444\\u0438\\u043b\\u044c-\\u0432\\u043e\\u043b\\u043d\\u043e\\u0432\\u043e\\u0439-\\u043a\\u0430\\u043c\\u0435\\u044f-(2).png\",\"desc\":\"\"},{\"MIGX_id\":\"3\",\"image\":\"\\u043f\\u0440\\u043e\\u0444\\u0438\\u043b\\u044c-\\u0432\\u043e\\u043b\\u043d\\u043e\\u0432\\u043e\\u0439-\\u043a\\u0430\\u043c\\u0435\\u044f-(3).png\",\"desc\":\"\"}]');
REPLACE INTO `modx_site_tmplvar_contentvalues` VALUES (30,10,19,'[{\"MIGX_id\":\"1\",\"brand\":\"Grand Line\",\"country_origin\":\"\\u0420\\u043e\\u0441\\u0441\\u0438\\u044f\",\"guarantee\":\"15 \\u043b\\u0435\\u0442\",\"material\":\"\\u041f\\u043e\\u043b\\u0438\\u044d\\u0444\\u0438\\u0440\",\"color_shade\":\"\\u041a\\u043e\\u0440\\u0438\\u0447\\u043d\\u0435\\u0432\\u044b\\u0439\",\"thickness\":\"0,45\",\"coating_thickness\":\"25\",\"overall_width\":\"1180\"}]');
/*!40000 ALTER TABLE `modx_site_tmplvar_contentvalues` ENABLE KEYS */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

