
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

/*!40000 ALTER TABLE `modx_site_content` DISABLE KEYS */;
REPLACE INTO `modx_site_content` VALUES (1,'document','Главная','Эксклюзивный представитель фасада и фасадных материалов в Беларуси','','home','',1,0,0,0,0,'','<p>Наружный фасад – важнейшая составляющая облика здания, которая создает первое впечатление  и формирует эстетику окружающей среды. Вентилируемые фасады являются по своим физико-строительным параметрам наиболее эффективными, многослойными системами, имеющими ветровой и дождевой барьер, они обеспечивают долговременную функциональную надежность зданий.</p>\r\n\r\n<p>Основные достоинства навесных вентилируемых фасадов:</p>\r\n\r\n<ul>\r\n<li>пожарная безопасность;</li>\r\n<li>высокая тепло- и звукоизоляция;</li>\r\n<li>экономия энергозатрат на отопление зданий, поддержание режима теплообмена (комфортные условия внутри здания зимой и летом);</li>\r\n<li>защита стены и теплоизоляции от атмосферных воздействий (талая вода, дождь, конденсат);</li>\r\n<li>вентиляция внутренних слоев — удаление атмосферной влаги и влаги, образующейся за счет диффузии водяных паров изнутри;</li>\r\n<li>высокоэффективная защита здания от ударов молнии;</li>\r\n<li>нивелирование термических деформаций;</li>\r\n<li>возможность проведения фасадных работ в любое время года — исключены «мокрые» процессы;</li>\r\n<li>отсутствие специальных требований к поверхности несущей стены — ее предварительное выравнивание, и более того, сама система позволяет выравнивать дефекты и неровности поверхности, что сделать с применением штукатурок часто сложно и дорого;</li>\r\n<li>простая процедура демонтажа;</li>\r\n<li>длительный безремонтный срок;</li>\r\n<li>широкие возможности по использованию современных фасадных отделочных материалов;</li>\r\n<li>эстетичный, престижный вид здания;</li>\r\n<li>многообразие цветовой гаммы фасада, длительная стойкость цвета, неограниченные возможности дизайна;</li>\r\n<li>соответствие экологическим стандартам.</li>\r\n</ul>',1,1,0,1,1,1,1743933618,1,1743968770,0,0,0,0,0,'',0,1,'MODX\\Revolution\\modDocument','web',1,'',0,0,1,NULL,1);
REPLACE INTO `modx_site_content` VALUES (2,'document','Наши преимущества','Наши преимущества','','our-advantages','',1,0,0,0,0,'','<h2>Наши преимущества</h2>\r\n\r\n<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eu urna massa. Ut non aliquam eros. Mauris ultrices auctor risus a tempus. Sed ex nibh, fringilla ac risus vitae, dapibus consectetur arcu. Maecenas a vehicula turpis, vitae maximus massa. Vivamus at magna lectus. Curabitur lobortis dictum rhoncus. Proin ullamcorper ornare commodo. Proin at lobortis massa. Nunc in rhoncus lacus, non tincidunt sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent mi sapien, efficitur ut pellentesque vel, condimentum eget ex. Donec volutpat dignissim diam, vitae blandit urna condimentum at.</p>\r\n\r\n<p>Sed ornare, neque luctus dignissim sollicitudin, diam neque condimentum felis, consequat fermentum justo sapien a orci. Nulla lobortis in nisl at iaculis. Maecenas at metus vehicula, maximus quam in, consequat nibh. Curabitur dictum congue ligula id eleifend. Fusce lobortis quis odio a placerat. Maecenas turpis urna, vulputate a molestie ac, commodo at diam. Cras sed lectus mollis, convallis lacus eget, dictum libero. Phasellus quis rhoncus tellus, sit amet porta lectus. Nulla congue euismod libero, in sodales magna. Curabitur eu tincidunt enim. Vestibulum vel malesuada felis.</p>',1,1,1,1,1,1,1743940955,1,1743968786,0,1743940987,1,1743955020,1,'',0,1,'MODX\\Revolution\\modDocument','web',1,'',0,0,1,NULL,1);
REPLACE INTO `modx_site_content` VALUES (3,'document','Каталог','Каталог','','catalog','',1,0,0,0,0,'','',1,3,2,1,1,1,1743954998,1,1744027556,0,0,0,1743955020,1,'',0,1,'MODX\\Revolution\\modDocument','web',1,'',0,0,1,NULL,1);
REPLACE INTO `modx_site_content` VALUES (4,'document','Наши работы','Наши работы','','our-works','',1,0,0,0,0,'','<h2>Наши Работы</h2>\r\n\r\n<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eu urna massa. Ut non aliquam eros. Mauris ultrices auctor risus a tempus. Sed ex nibh, fringilla ac risus vitae, dapibus consectetur arcu. Maecenas a vehicula turpis, vitae maximus massa. Vivamus at magna lectus. Curabitur lobortis dictum rhoncus. Proin ullamcorper ornare commodo. Proin at lobortis massa. Nunc in rhoncus lacus, non tincidunt sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent mi sapien, efficitur ut pellentesque vel, condimentum eget ex. Donec volutpat dignissim diam, vitae blandit urna condimentum at.</p>\r\n\r\n<p>Sed ornare, neque luctus dignissim sollicitudin, diam neque condimentum felis, consequat fermentum justo sapien a orci. Nulla lobortis in nisl at iaculis. Maecenas at metus vehicula, maximus quam in, consequat nibh. Curabitur dictum congue ligula id eleifend. Fusce lobortis quis odio a placerat. Maecenas turpis urna, vulputate a molestie ac, commodo at diam. Cras sed lectus mollis, convallis lacus eget, dictum libero. Phasellus quis rhoncus tellus, sit amet porta lectus. Nulla congue euismod libero, in sodales magna. Curabitur eu tincidunt enim. Vestibulum vel malesuada felis.</p>',1,1,3,1,1,1,1743955069,1,1743968792,0,0,0,1743955080,1,'',0,1,'MODX\\Revolution\\modDocument','web',1,'',0,0,1,NULL,1);
REPLACE INTO `modx_site_content` VALUES (5,'document','Шоурум','Шоурум','','showroom','',1,0,0,0,0,'','<h2>Шоурум</h2>\r\n\r\n<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eu urna massa. Ut non aliquam eros. Mauris ultrices auctor risus a tempus. Sed ex nibh, fringilla ac risus vitae, dapibus consectetur arcu. Maecenas a vehicula turpis, vitae maximus massa. Vivamus at magna lectus. Curabitur lobortis dictum rhoncus. Proin ullamcorper ornare commodo. Proin at lobortis massa. Nunc in rhoncus lacus, non tincidunt sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent mi sapien, efficitur ut pellentesque vel, condimentum eget ex. Donec volutpat dignissim diam, vitae blandit urna condimentum at.</p>\r\n\r\n<p>Sed ornare, neque luctus dignissim sollicitudin, diam neque condimentum felis, consequat fermentum justo sapien a orci. Nulla lobortis in nisl at iaculis. Maecenas at metus vehicula, maximus quam in, consequat nibh. Curabitur dictum congue ligula id eleifend. Fusce lobortis quis odio a placerat. Maecenas turpis urna, vulputate a molestie ac, commodo at diam. Cras sed lectus mollis, convallis lacus eget, dictum libero. Phasellus quis rhoncus tellus, sit amet porta lectus. Nulla congue euismod libero, in sodales magna. Curabitur eu tincidunt enim. Vestibulum vel malesuada felis.</p>',1,1,4,1,1,1,1743955117,1,1744024634,0,0,0,1743955080,1,'',0,1,'MODX\\Revolution\\modDocument','web',1,'',0,0,1,NULL,1);
REPLACE INTO `modx_site_content` VALUES (6,'document','Товары','','','товары','',1,0,0,0,1,'','',1,3,6,1,1,1,1743963283,1,1744026211,0,0,0,1744026211,1,'',0,0,'MODX\\Revolution\\modDocument','web',1,'',0,0,1,NULL,1);
REPLACE INTO `modx_site_content` VALUES (10,'document','Сайдинг наружный виниловый Альта-Профиль Классика, Светло-серый','','','сайдинг-наружный-виниловый-альта-профиль-классика,-светло-серый','',1,0,0,6,0,'','',1,2,0,1,1,1,1743965296,1,1744029415,0,0,0,1744024560,1,'',0,0,'MODX\\Revolution\\modDocument','web',1,'',0,0,1,NULL,1);
REPLACE INTO `modx_site_content` VALUES (16,'document','ЭкоБрус 0,345 0,45 PE с пленкой','','','экобрус','',1,0,0,6,0,'','',1,2,1,1,1,1,1743978211,1,1744038247,0,0,0,1744025340,1,'',0,0,'MODX\\Revolution\\modDocument','web',1,'',0,0,1,NULL,1);
REPLACE INTO `modx_site_content` VALUES (17,'document','Вертикаль 0,2 gofr 0,5 Satin с пленкой','','','вертикаль-0,2-gofr-0,5-satin-с-пленкой','',1,0,0,6,0,'','',1,2,2,1,1,1,1744040000,1,1744040189,0,0,0,1744040189,1,'',0,0,'MODX\\Revolution\\modDocument','web',1,'',0,0,1,NULL,1);
REPLACE INTO `modx_site_content` VALUES (18,'document','Корабельная Доска 0,265 0,5 Satin с пленкой','','','корабельная-доска-satin','',1,0,0,6,0,'','',1,2,3,1,1,1,1744040248,1,1744040997,0,0,0,1744040880,1,'',0,0,'MODX\\Revolution\\modDocument','web',1,'',0,0,1,NULL,1);
REPLACE INTO `modx_site_content` VALUES (19,'document','Профиль волновой Камея','','','профиль-волновой-камея','',1,0,0,6,0,'','',1,2,4,1,1,1,1744041014,1,1744120964,0,0,0,1744041240,1,'',0,0,'MODX\\Revolution\\modDocument','web',1,'',0,0,1,NULL,1);
/*!40000 ALTER TABLE `modx_site_content` ENABLE KEYS */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

