
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

/*!40000 ALTER TABLE `modx_menus` DISABLE KEYS */;
REPLACE INTO `modx_menus` VALUES ('{$username}','user','security/profile','profile_desc','',0,'','','change_profile','core');
REPLACE INTO `modx_menus` VALUES ('about','usernav','help','about_desc','<i class=\"icon-question-circle icon\"></i>',3,'','','help','core');
REPLACE INTO `modx_menus` VALUES ('access','usernav','','','<i class=\"icon-user-lock icon\"></i>',1,'','','access_permissions','core');
REPLACE INTO `modx_menus` VALUES ('acls','access','security/permission','acls_desc','',2,'','','access_permissions','core');
REPLACE INTO `modx_menus` VALUES ('admin','usernav','','','<i class=\"icon-gear icon\"></i>',2,'','','settings','core');
REPLACE INTO `modx_menus` VALUES ('components','topnav','','','<i class=\"icon-cube icon\"></i>',2,'','','components','core');
REPLACE INTO `modx_menus` VALUES ('content_types','site','system/contenttype','content_types_desc','',4,'','','content_types','core');
REPLACE INTO `modx_menus` VALUES ('contexts','admin','context','contexts_desc','',4,'','','view_context','core');
REPLACE INTO `modx_menus` VALUES ('dashboards','admin','system/dashboards','dashboards_desc','',5,'','','dashboards','core');
REPLACE INTO `modx_menus` VALUES ('edit_menu','admin','system/action','edit_menu_desc','',3,'','','actions','core');
REPLACE INTO `modx_menus` VALUES ('eventlog_viewer','reports','system/event','eventlog_viewer_desc','',1,'','','view_eventlog','core');
REPLACE INTO `modx_menus` VALUES ('file_browser','media','media/browser','file_browser_desc','',0,'','','file_manager','core');
REPLACE INTO `modx_menus` VALUES ('flush_access','access','','flush_access_desc','',3,'','MODx.msg.confirm({\n                            title: _(\'flush_access\')\n                            ,text: _(\'flush_access_confirm\')\n                            ,url: MODx.config.connector_url\n                            ,params: {\n                                action: \'security/access/flush\'\n                            }\n                            ,listeners: {\n                                \'success\': {fn:function() { location.href = \'./\'; },scope:this},\n                                \'failure\': {fn:function(response) { Ext.MessageBox.alert(\'failure\', response.responseText); },scope:this},\n                            }\n                        });','access_permissions','core');
REPLACE INTO `modx_menus` VALUES ('flush_sessions','access','','flush_sessions_desc','',4,'','MODx.msg.confirm({\n                            title: _(\'flush_sessions\')\n                            ,text: _(\'flush_sessions_confirm\')\n                            ,url: MODx.config.connector_url\n                            ,params: {\n                                action: \'security/flush\'\n                            }\n                            ,listeners: {\n                                \'success\': {fn:function() { location.href = \'./\'; },scope:this}\n                            }\n                        });','flush_sessions','core');
REPLACE INTO `modx_menus` VALUES ('form_customization','admin','security/forms','form_customization_desc','',1,'','','customize_forms','core');
REPLACE INTO `modx_menus` VALUES ('installer','components','workspaces','installer_desc','',0,'','','packages','core');
REPLACE INTO `modx_menus` VALUES ('language','admin','','language_desc','',8,'','','language','core');
REPLACE INTO `modx_menus` VALUES ('lexicon_management','admin','workspaces/lexicon','lexicon_management_desc','',7,'','','lexicons','core');
REPLACE INTO `modx_menus` VALUES ('logout','user','security/logout','logout_desc','',2,'','MODx.logout(); return false;','logout','core');
REPLACE INTO `modx_menus` VALUES ('media','topnav','','','<i class=\"icon-file-image-o icon\"></i>',1,'','','file_manager','core');
REPLACE INTO `modx_menus` VALUES ('messages','user','security/message','messages_desc','',1,'','','messages','core');
REPLACE INTO `modx_menus` VALUES ('MIGX','components','index','','',1,'&configs=migxconfigs||packagemanager','','','migx');
REPLACE INTO `modx_menus` VALUES ('namespaces','admin','workspaces/namespace','namespaces_desc','',6,'','','namespaces','core');
REPLACE INTO `modx_menus` VALUES ('new_resource','site','resource/create','new_resource_desc','',0,'','','new_document','core');
REPLACE INTO `modx_menus` VALUES ('propertysets','admin','element/propertyset','propertysets_desc','',2,'','','property_sets','core');
REPLACE INTO `modx_menus` VALUES ('refresh_site','site','','refresh_site_desc','',1,'','MODx.clearCache(); return false;','empty_cache','core');
REPLACE INTO `modx_menus` VALUES ('refreshuris','refresh_site','','refreshuris_desc','',0,'','MODx.refreshURIs(); return false;','empty_cache','core');
REPLACE INTO `modx_menus` VALUES ('remove_locks','site','','remove_locks_desc','',2,'','MODx.removeLocks();return false;','remove_locks','core');
REPLACE INTO `modx_menus` VALUES ('reports','admin','','reports_desc','',9,'','','menu_reports','core');
REPLACE INTO `modx_menus` VALUES ('resource_groups','access','security/resourcegroup','resource_groups_desc','',1,'','','access_permissions','core');
REPLACE INTO `modx_menus` VALUES ('site','topnav','','','<i class=\"icon-file-text-o icon\"></i>',0,'','','menu_site','core');
REPLACE INTO `modx_menus` VALUES ('site_schedule','site','resource/site_schedule','site_schedule_desc','',3,'','','view_document','core');
REPLACE INTO `modx_menus` VALUES ('sources','media','source','sources_desc','',1,'','','sources','core');
REPLACE INTO `modx_menus` VALUES ('system_settings','admin','system/settings','system_settings_desc','',0,'','','settings','core');
REPLACE INTO `modx_menus` VALUES ('topnav','','','topnav_desc','',0,'','','','core');
REPLACE INTO `modx_menus` VALUES ('trash','site','resource/trash','trash_desc','',5,'','','menu_trash','core');
REPLACE INTO `modx_menus` VALUES ('user','usernav','','','<span id=\"user-avatar\" title=\"{$username}\">{$userImage}</span> <span id=\"user-username\">{$username}</span>',0,'','','menu_user','core');
REPLACE INTO `modx_menus` VALUES ('usernav','','','usernav_desc','',1,'','','','core');
REPLACE INTO `modx_menus` VALUES ('users','access','security/user','user_management_desc','',0,'','','view_user','core');
REPLACE INTO `modx_menus` VALUES ('view_logging','reports','system/logs','view_logging_desc','',0,'','','mgr_log_view','core');
REPLACE INTO `modx_menus` VALUES ('view_sysinfo','reports','system/info','view_sysinfo_desc','',2,'','','view_sysinfo','core');
/*!40000 ALTER TABLE `modx_menus` ENABLE KEYS */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

